### ISSUE TITLE
Not able to run in Mac  ( v10.9.3 )

### ISSUE THREAD

**Issue by 29jitender** [romannurik/AndroidDesignPreview#1]
![screen shot 2014-05-20 at 10 33 18 pm](https://cloud.githubusercontent.com/assets/940288/3030410/b900f266-e040-11e3-9fad-7193ecc41fac.png)

**Comment by romannurik** [comment]
Another option is to right click the .app and press Open. This for some reason allows you to skip the security check.

**Comment by romannurik** [comment]
Yet another option is to remove extended attributes on the `.app` file:

`xattr -rc Android\ Design\ Preview.app`

**WARNING: Don't do this for untrusted apps.**
