### ISSUE TITLE
Broken link in release comments.

### ISSUE THREAD

**Issue by danielgomezrico** [romannurik/AndroidDesignPreview#10]
"is damaged and can't be opened" error" link broken

**Comment by romannurik** [comment]
Duplicate of #1

**Comment by eddiecubed** [comment]
He is referring to the link in the release notes for v0.3.2 is broken.
The link can be found on this page: https://github.com/romannurik/AndroidDesignPreview/releases

**Comment by romannurik** [comment]
Ah, fixed.

**Comment by danielgomezrico** [comment]
:+1:

**Comment by joesmarkez** [comment]
Genial para poder y tener a la mano un buen trabajo
