### ISSUE TITLE
Not able to run on mac (10.9.2)

### ISSUE THREAD

**Issue by mfreiberger** [romannurik/AndroidDesignPreview#3]
I have the same issue as 29jitender with the mac (10.9.3) had.

I have the same error and I had allowed the download via the Security and Privacy as you had stated, but I then get this dialog when I try to launch the program.
![screen shot 2014-06-02 at 12 00 17 pm](https://cloud.githubusercontent.com/assets/7772126/3151967/9dbe6de2-ea88-11e3-8900-d19438c9d306.png)

**Comment by romannurik** [comment]
This is a dup of #1
