### ISSUE TITLE
Yosemite “Android Design Preview” is damaged and can’t be opened. 

### ISSUE THREAD

**Issue by mattgraham** [romannurik/AndroidDesignPreview#5]
I'm getting: “Android Design Preview” is damaged and can’t be opened. You should move it to the Trash; when I attempt to run design preview in Yosemite (not sure what this is doing in other versions). I'm not sure if this is known or unknown but I thought I'd drop in the notification.

**Comment by romannurik** [comment]
This is a dup of #1
