### ISSUE TITLE
The mirror region is bigger than my screen

### ISSUE THREAD

**Issue by 109021017** [romannurik/AndroidDesignPreview#8]
The mirror region is bigger than my screen on my MacBook with a Retina display.
![untitled-2](https://cloud.githubusercontent.com/assets/2888378/7099746/f22c396c-e02e-11e4-9514-7b1720da7a56.jpg)
Is there a way to set the scale.

**Comment by romannurik** [comment]
If you drag the mirror region such that you can see a corner, you can then drag the corners to resize.
